In [1]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv(r"C:\Users\saran\Downloads\Churn_Modelling (1).csv")

In [3]:
x=df.iloc[:,3:13].values
y = df.iloc[:,13].values

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          608     Spain  Female  41.0   
2          3    15619304      Onio          502    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [7]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2 = LabelEncoder()
x[:,2]= labelencoder_x_2.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], shape=(10000, 10), dtype=object)

In [71]:
# Splitting the dataset into the training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [72]:
len(x_train)

8000

In [73]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [39]:
# Classical ML

from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier()
dt.fit(x_train,y_train)
pred= dt.predict(x_test)

In [40]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,pred)

In [41]:
cm

array([[1362,  233],
       [ 190,  215]])

In [42]:
# Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,pred)
print("Accuracy of Decision Tree Classifier: ",score*100)

Accuracy of Decision Tree Classifier:  78.85


In [43]:
# Using Random Forest
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier(n_estimators=100)
rf.fit(x_train , y_train)
pred2= rf.predict(x_test)

In [44]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test,pred2)

In [45]:
cm2

array([[1527,   68],
       [ 200,  205]])

In [46]:
# Accuracy
from sklearn.metrics import accuracy_score
score2 = accuracy_score(y_test,pred2)
print("Accuracy of Random Forest Classifier: ",score2*100)

Accuracy of Random Forest Classifier:  86.6


### ANN

In [47]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [48]:
# Initializing te ANN
classifier= Sequential()
# units: its an art, comes by experience. input+output/2
#initializer: how weights are updated
# relu activation function
# input_dim: input shape(shape of the data, how many features do we have in the data)
#adding the input layer and the first hidden layer
classifier.add(Dense(units = 6 , kernel_initializer='uniform', activation='relu',input_dim=10))
# Adding the second hidden layer
classifier.add (Dense(units=6, kernel_initializer='uniform', activation='relu'))

#  Adding the third hidden layer
classifier.add (Dense(units=6, kernel_initializer='uniform', activation='relu'))

#Adding the output
classifier.add (Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

# This entire code means firstly we have 10 neurons then there are 3 hidden layer which have 6 neurons each and then output layer. 

C:\Users\saran\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [49]:
len(x_train)

8000

In [50]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
y_train[0]
# Fitting the ANN to the Training set
classifier.fit(x_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7955 - loss: 0.5409
Epoch 2/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7960 - loss: 0.5061
Epoch 3/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7960 - loss: 0.5061
Epoch 4/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 5/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 6/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 7/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 8/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 9/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 10/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7960 - loss: 0.5061
Epoch 11/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 12/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step

In [51]:
# making predictions and evaluating the model
y_pred_ann = classifier.predict(x_test)
y_pred_ann = (y_pred_ann >0.5)

cm3= confusion_matrix(y_test, y_pred_ann)
print(cm3)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
[[1595    0]
 [ 405    0]]


In [52]:
from sklearn.metrics import accuracy_score
score3 = accuracy_score(y_test, y_pred_ann)
print(score3*100)

79.75


## Conclusion:

So, as we have already seen, by using 2 hidden layered ANN, we aren't able to get beyond 85% accuracy, ofcourse we can get higher accuracy by increasing the epochs( not in this example) & doing some hyperparameter tuning, so on the other hand, the classical models can also be tuned further.

Bottomline, always start with classical machine learning models, and if we aren't able to increase the performance, then move towards Deep Learning techniques :)

## Hyperparameter Optimization

In [77]:
np.isnan(x_train).sum()


np.int64(250)

In [78]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")
x_train = imputer.fit_transform(x_train)


In [79]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.pipeline import Pipeline

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units=6, kernel_initializer = 'uniform' ,activation= 'relu', input_dim=10))
    classifier.add(Dense(units=6, kernel_initializer = 'uniform' ,activation= 'relu'))
    classifier.add(Dense(units=1, kernel_initializer = 'uniform' ,activation= 'sigmoid'))
    classifier.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier= KerasClassifier(model = build_classifier , batch_size=10, epochs =10, verbose=0)
pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
    ("ann", classifier)
])

accuracies = cross_val_score(
    estimator=pipeline,
    X=x_train,
    y=y_train,
    cv=10,
    n_jobs=-1)
mean1 = accuracies.mean()
variance= accuracies.std()

In [80]:
accuracies

array([0.82875, 0.84   , 0.84125, 0.83875, 0.8475 , 0.8325 , 0.8425 ,
       0.81875, 0.8125 , 0.8325 ])

In [81]:
mean1

np.float64(0.8334999999999999)

In [82]:
variance

np.float64(0.010440306508910561)

In [83]:
# improving the ANN classifier

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_classifier():
    model = Sequential()
    model.add(Dense(6, activation="relu", kernel_initializer="uniform", input_dim=10))
    model.add(Dense(6, activation="relu", kernel_initializer="uniform"))
    model.add(Dense(1, activation="sigmoid", kernel_initializer="uniform"))
    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )
    return model
classifier = KerasClassifier(
    model=build_classifier,
    verbose=0
)
pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
    ("ann", classifier)
])
parameters = {
    "ann__batch_size": [10, 20],
    "ann__epochs": [5, 6]
}
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=parameters,
    scoring="accuracy",
    cv=5,
    n_jobs=-1
)

grid_search.fit(x_train, y_train)

best_params = grid_search.best_params_
best_score = grid_search.best_score_

print(best_params)
print(best_score)


C:\Users\saran\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


{'ann__batch_size': 10, 'ann__epochs': 6}
0.8225


can do randomizedsearchcv also

## Improvising the performance of ANN

1. Increasing the number of hidden layers
2. Increasing the number of epochs
3. Fine-tuning the parameters - optimizers, batch_size, epochs
4. Dropout regularization: Dropout(0.25)

Overfitting problem --> training accuracy increases, but test accuracy is low